### ISSUE TITLE
Quarks on Raspberry PI

### ISSUE THREAD

**Issue by jms90h5** [quarks-edge/quarks#119]
I've been thinking about picking up a Raspberry Pi 3 specifically to try running Quarks on it.   Has anyone tried running Quarks on one of the earlier versions?  Did you have any issues?  

Given the utility of Quarks for edge devices, a Raspberry Quark Pi would seem like a really logical dessert. :)

**Comment by wmarshall484** [comment]
Yup! I've used Quarks on the Raspberry Pi 2B with success. The Raspberry Pi3 looks like a great piece of hardware. If you try it, let us know how it handles!

**Comment by ddebrunner** [comment]
I ran the demo shown in this presentation on the older Raspberry Pi B (car OBD-II data, K-Means clustering, connection to Streams through Watson IoT Platform):

https://ibm.box.com/s/j50ktov45r28cyj6lkeu6habzmpwapdp

The only requirement is to have a JVM, and now Raspbian includes a Java 8 vm by default.

**Comment by ddebrunner** [comment]
A Raspberry Pi Zero would be interesting to try ...

**Comment by jms90h5** [comment]
Although I was originally thinking about the new 3 for a more performance demanding application, I agree about the zero for a super low cost edge or embedded device.  Since William already verified that Quarks can work (I'm assuming on Raspbian) now I just need to find some place that has some in stock outside of bundles.

**Comment by ddebrunner** [comment]
I've heard someone has run it successfully on a Raspberry Pi 3.
