### ISSUE TITLE
Link to current committers does not work

### ISSUE THREAD

**Issue by home4slc** [quarks-edge/quarks#12]
When browsing through the web site: http://quarks-edge.github.io/

If I go to this page:
http://quarks-edge.github.io/quarks.documentation/docs/quarks/committers/
it works, but if I go to the 'Current committers' page it does not:
1. https://github.com/orgs/quarks-edge/teams/quarkscommitters
2. On this page:
   http://quarks-edge.github.io/quarks.documentation/docs/quarks/quarks-getting-started/
   The section called 'Adding the console to your application' has formatting issues.  It is difficult to tell the lines of code from the comments section.

If I find other broken links or areas with formatting that needs improvement, I'll add them to this issue.  Thanks!

**Comment by ddebrunner** [comment]
Can you enter this as issues in the appropriate projects.

**Comment by home4slc** [comment]
Yes, I incorrectly entered it on the wrong site.  My apologies.
