### ISSUE TITLE
Copyright statement in Java samples

### ISSUE THREAD

**Issue by vlasov01** [quarks-edge/quarks#19]
Java samples have a header, which states the following:

```
/*
# Licensed Materials - Property of IBM
# Copyright IBM Corp. 2015, 2016 
*/
```

I think it doesn't match the project license.

**Comment by ddebrunner** [comment]
That's a copyright statement, not a licencing statement.

The code was originally developed and therefore owned by IBM.

IBM is releasing it under the Apache License Version 2.

When any code is released under the Apache License Version 2 (or any license) it still has an owner who owns the copyright and can, if they choose to, release additionally under a different license.

**Comment by vlasov01** [comment]
Thank you for the clarification.
So under the Apache License Version 2 I can modify a file with a such copyright statement, but I need to keep a copyright statement as is. Is it correct?

**Comment by ddebrunner** [comment]
I believe so, I'm not a laywer, but as far as I understand only the copyright holder (IBM in this case) can remove a copyright notice.

**Comment by vlasov01** [comment]
Thank you!

**Comment by home4slc** [comment]
So for new files that are added to quarks, should the IBM copyright be applied to the new file?

**Comment by ddebrunner** [comment]
@home4slc - only if it's developed by someone who works for IBM.

**Comment by home4slc** [comment]
@ddebrunner  - okay, thanks
