### ISSUE TITLE
Cannot rebase upstream/master

### ISSUE THREAD

**Issue by home4slc** [quarks-edge/quarks#23]
I'm trying to create a new branch so I can work on an issue this morning, however I can not do a rebase upstream/master.

Here is what I have done so far:

  git checkout master  <-- works
  git fetch upstream <-- works
  git rebase upstream/master <-- does not work:

Susans-MacBook-Pro-247:quarks susancline$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
error: The following untracked working tree files would be overwritten by checkout:
    samples/connectors/src/main/java/quarks/samples/connectors/iotf/IotfSensors.java
Please move or remove them before you can switch branches.
Aborting
could not detach HEAD

Does anyone know how to fix this so I can proceed?

Susans-MacBook-Pro-247:quarks susancline$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by ddebrunner** [comment]
I keep a clean clone of my fork that I use for rebasing my fork from quarks-edge/quarks.
I never do any development in this clone, just rebase from the upstream and then push it back to my fork.

After that my fork says it's even with quarks-edge/quarks.

So I would try creating a clean clone of your fork and see if you can bring your fork to be even with quarks-edge/quarks.

**Comment by chanskw** [comment]
I use Github Desktop and Atom Editor ... which helps with rebase and merging a lot.

**Comment by bjhargrave** [comment]
> First, rewinding head to replay your work on top of it...
> error: The following untracked working tree files would be overwritten by checkout:
> samples/connectors/src/main/java/quarks/samples/connectors/iotf/IotfSensors.java
> Please move or remove them before you can switch branches.
> Aborting
> could not detach HEAD

This is because of a file rename which changed only the case of the file name. 

```
$ git show 0d7e5c295963a54c76515adc8069800c8f21db16 --stat
commit 0d7e5c295963a54c76515adc8069800c8f21db16
Author: Daniel J. Debrunner <debrunne@us.ibm.com>
Date:   Tue Feb 16 12:25:46 2016 -0800

    Rename IoTFSensors to IotfSensors to be consistent

 samples/connectors/src/main/java/quarks/samples/connectors/iotf/IoTFSensors.java | 121 ----------------------------------------------------------
 samples/connectors/src/main/java/quarks/samples/connectors/iotf/IotfSensors.java | 127 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 scripts/connectors/iotf/device.cfg                                               |   7 ++++
 scripts/connectors/iotf/runiotfsensors.sh                                        |  15 ++++++--
 scripts/device.cfg                                                               |   7 ----
 5 files changed, 145 insertions(+), 132 deletions(-)
```

You are probably using a case insensitive file system (default on OS X). Do you have `$ git config core.ignorecase` set to `true`?

**Comment by dlaboss** [comment]
yup.  `git config --add core.ignorecase true` make things work for me / my mac... then saw your response.  Is it always supposed to be set?  This particular clone was created via Eclipse/git and its config lacked anything for core.ignorecase.  I looked at another clone I had for another repo, that I created manually, not via Eclipse/git, and it did have core.ignorecase=true.  I don't recall manually adding that before.

**Comment by bjhargrave** [comment]
I don't trust the jgit impl in Eclipse. I use command line git :-) Command line git detects case insensitive file systems during git init/clone and sets the config variable properly. I suspect jgit does not even try.

**Comment by dlaboss** [comment]
I know what you mean.  I still do all my fetch/rebase from the cli.

**Comment by home4slc** [comment]
I'm good now, thanks everyone.
