### ISSUE TITLE
Add a WebSocket connector

### ISSUE THREAD

**Issue by dlaboss** [quarks-edge/quarks#29]
Features:
- Web Socket Client
- Web Socket Server
- support binary and string payloads

pull #32 contains the proposed API

**Comment by wmarshall484** [comment]
This was requested by a number of customers at Spark Summit.

**Comment by ddebrunner** [comment]
@wmarshall484 Any example usage scenarios, rather than just websockets are needed?

**Comment by wmarshall484** [comment]
@dlaboss @ddebrunner  Meant to say "potential users" not "customers".

One potential user has a chat-based social network startup. From what I understood, the chat client (nonspecific as to whether this was a phone) opens a websocket connection with a server. In addition to sending the chat messages, the client also performs sentiment analysis on the users' messages. The use case for Quarks would be to only send user sentiment back to the server when it goes outside of a certain range (e.g, the last 25 messages the user sent were unusually happy or sad, make a note of this).

He didn't say in what format the messages are sent, but as it's a chat service I suspect JSON, or encrypted JSON, would be likely.

**Comment by dlaboss** [comment]
Initial delivery merged by #32
- add "ws" support.  ("wss" also works for against servers with non-self-signed certs and no client auth)
- add WebSocketClient API, Jsr356WebSocketClient generic javax.websocket based impl
- add javax.websocket-client and javax.websocket-server JSR356 impls provided by Eclipse Jetty jars.
- update overview-summary connector table and connector use instructions
- add "ws" tests

Full "wss" support is next.
