### ISSUE TITLE
Running unit tests shows many stack traces.

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks#36]
https://travis-ci.org/quarks-edge/quarks/builds/110987853

For clarity if a test is throwing an exception for testing it's useful to have its message include "Expected Test Exception" or similar to avoid people unfamiliar with the test wasting time trying to track down the exception.

In addition, is it needed that the trace is printed for any expected exceptions? Gives the impression there is an issue.

**Comment by vdogaru** [comment]
Yes, I agree that exceptions injected into tests should have an explanatory message.

> Is it needed that the trace is printed for any expected exceptions?

Several tests use injected exceptions to test system behavior on handling uncaught exceptions.
From the system's perspective these exceptions are unexpected. The current behavior is to print the exception stack trace to System.err and shut down the runtime. Exceptions will be logged instead.

**Comment by vdogaru** [comment]
See [pull request 51](https://github.com/quarks-edge/quarks/pull/51)

**Comment by vdogaru** [comment]
No more stack traces in https://travis-ci.org/quarks-edge/quarks/builds/111627902

**Comment by dlaboss** [comment]
Re: that build results file, why do tests, e.g., DirectJobTest, still generate slf4j complaints like the following?  I thought an slf4j impl jar inclusion had been added to the build harness for samples, etc?

```
    [junit] ------------- Standard Error -----------------
    [junit] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    [junit] SLF4J: Defaulting to no-operation (NOP) logger implementation
    [junit] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by ddebrunner** [comment]
@dlaboss I would guess that the unit tests do not include the samples jar in the classpath. The unit tests include the minimal classpath to help ensure no incorrect dependencies.

The unit tests could have the slf4j impl jar included.

**Comment by vdogaru** [comment]
[Pull request 66](https://github.com/quarks-edge/quarks/pull/66) adds slf4j binding to Java logging.  This stop unit tests from writing `[junit] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"` on System.err.  Can be verified by running:

```
ant clean all test reports
grep -nRH 'SLF4J' ./reports/junit/quarks/test
```

**Comment by vdogaru** [comment]
https://travis-ci.org/quarks-edge/quarks/builds/112766712

#66 and #67 fix the following issues:
- All JUnit tests run with slf4j configured to write logs through the Java Logging API -- the default configuration is to write logs to System.err.
- Unexpected exceptions caught by Quarks are reported in the logs. A logged exception does not necessarily indicate an uncaught system failure -- connectors, for example, throw exceptions on connect failure, but then the system retries the operation.
- Some tests inject exceptions to test the system behavior on error conditions. For clarity these have the message "Expected Test Exception".
