### ISSUE TITLE
Add batch support to the Quarks windowing API

### ISSUE THREAD

**Issue by wmarshall484** [quarks-edge/quarks#37]
The API changes are the following additions to TWindow<T,K>:

"<b>
TStream<B> batch(BiFunction<List<T>,K,B> batcher)
TStream<B> batch(BiFunction<List<T>,K,B> batcher, long time, TimeUnit unit)
</b>
Process a window in batches. batcher is called when a partition in this window is complete.

Once a partition in this window is complete batcher is called passing the current contents of the partition. When batcher returns, the partition contents are discarded and the partition starts to fill again, the window partition tumbles.

This means the window partition is processed in non-overlapping batches, a tuple is only processed once by batcher.

For a count based window of size N a partition becomes complete when it contains N tuples.

For example with last(10) batcher will be called after the partition has received ten tuples passing the first ten tuples (1-10), then after a further ten tuples have been received batcher is called passing tuples 11-20, etc. Thus at the time the partition is visible, when batcher is called, the partition contains the last ten tuples on the stream for its key, which is its definition.

For time based windows a partition of S seconds becomes complete (approximately) every S seconds starting when it receives its first tuple on the stream. If no tuples arrived during the time the partition was waiting to become complete then batcher is called passing an empty list of tuples.

For example last(5, SECONDS) at the time the partition is visible, when batcher is called, the partition contains the last fives seconds of tuples on the stream for its key, which is its definition."

**Comment by dlaboss** [comment]
+1 on batch support.  
What are the semantics/use of `TWindow.batch(fn, time, unit)`?  The description above seems to imply that only `batch(fn)` is needed - it's used for both count (`last(N)`) and time (`last(t,unit)`) based windows.

**Comment by wmarshall484** [comment]
Ah, you're right. The `TWindow.batch(fn, time, unit)` is an error on my part; it shouldn't have been included. There should be three functions total related to batch support:

``` Java
// In TStream
TWindow<T, K> last(int count, Function<T, K> keyFunction);
TWindow<T, K> last(long time, TimeUnit unit, Function<T, K> keyFunction);
```

and 

``` Java
// In TWindow
TStream<B> batch(BiFunction<List<T>, K, B> batcher);
```

When you define a `TWindow` with `TStream.last(count, fn)` and then call `TWindow.batch(batcher)`, `batcher` will get called whenever the size of the window reaches `count`. All the tuples in the window are then evicted. Rinse, repeat for the new tuples on the stream.

When you define a `TWindow` with `TStream.last(time, timeunit, fn)` and then call `TWindow.batch(batcher)`, `batcher` will get called every `time` seconds (or whichever `timeunit` is chosed). Afterwards, all the tuples in the window are then evicted. Again, rinse, repeat for the new tuples on the stream.

**Comment by wmarshall484** [comment]
Added with #62
