### ISSUE TITLE
Feedback for /

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks#4]
At the top under "Quarks Documentation" it says:

Documentation for Quarks Project

Which is not very helpful, seems like a brief overview of what Quarks is would be useful here.

**Comment by ddebrunner** [comment]
Reopened in quarks.documentation.

**Comment by kathyssaunders** [comment]
I think this page needs to be fixed as well:  http://quarks-edge.github.io/quarks.documentation/index.html

**Comment by ddebrunner** [comment]
Not a code issue.
