### ISSUE TITLE
Tag naming convention

### ISSUE THREAD

**Issue by vdogaru** [quarks-edge/quarks#40]
- Each  tag has a unique name, which is a simple dotted name, like "com.myapp.MyFilter".
  This allows developers to encode context info directly into a tag's name.  
- Quarks does not check a tag name for compliance to this notation rule.
  Developers are encouraged to follow this convention usage in order to avoid
  name clashes with tags generated by Quarks or other Quarks applications.
- Tags starting with 'quarks' are reserved for use by Quarks.
  A set of helper methods are used for easily creating tag names:

_Is there a better place to add these to, instead of default Tagable methods?_

```
    /**
     * Concatenates a class name and additional names to form a string where 
     * elements are separated by dots.
     * <p>
     * Empty or null names are ignored.
     */
    default String name(Class<?> clazz, String... names) {
        ...
    }

    /**
     * Concatenates the specified firstName and additional names to form a 
     * string where elements are separated by dots.
     * <p>
     * Empty or null strings are ignored.
     */
    default String name(String firstName, String... names) {
       ... 
    }
```

**Comment by dlaboss** [comment]
does `default` violate the Java8/Android rules?  Maybe just a `Tags` class?

**Comment by vdogaru** [comment]
Moved to https://issues.apache.org/jira/browse/QUARKS-68
