### ISSUE TITLE
Expose more tag information in the console

### ISSUE THREAD

**Issue by home4slc** [quarks-edge/quarks#42]
While writing a sample application for the console I realized we need more tag support exposed in the console.  Today I noticed 3 issues opened also relating to tagging: #39 , #40 , #41 .

Here are some thoughts about how the console could be improved wrt tagging:
1. Topology graph representation: Make the color of the oplets light grey when 'View by' is set to 'Stream tags'.  Also, change the legend circles that show the tag color to squares to more closely mimic the stream dimensions - not to be confused with the circles that represent the oplets.
2. Allow the user to select one, some or all tags to view in the topology graph at one time
3. Add tag information to all popups: 
   The 'View all oplet properties'
   The hover over the oplet
   The hover over the stream

Additional thoughts folks have??

**Comment by ddebrunner** [comment]
I'm thinking that I would tag a source stream with its sensor type, e.g. temperature, revs, speed etc.

Then from a view of the graph I can easily see which stream is which. So not so much a view by tag but the tags help me understand my flow.

**Comment by home4slc** [comment]
@ddebrunner - not sure I understand what you mean.  After starting to write a sample application, this is what would help me and I'm thinking it might help others.  If this is different then what you are saying let me know.
I have multiple sensors for one location / object and I tag each of those sensors identifying them as coming from the common location.  I can select view by whatever I tag each location as, or I can just show all tags, so that as the topology progresses I can see all of the individual streams that came from a common location.

If this is not what you mean can you explain further? Thanks!

**Comment by home4slc** [comment]
@ddebrunner - I was thinking about this some more.  What about having an option to either 'show tags' or not for the static and oplet kind views and remove the view by altogether for stream tags?  I'd also have an option to select one or more tags, and then a way to  pick 'show all tags'.

**Comment by home4slc** [comment]
See pull request #72 for information about what was included in this commit
