### ISSUE TITLE
iotf connector and javax.servlet

### ISSUE THREAD

**Issue by dlaboss** [quarks-edge/quarks#43]
@ddebrunner what's the scoop with the presence of iotf/ext/lib/javax.servlet_3.0.0.jar?
Is that cruft from a dependency of an earlier version of com.ibm.iotf.client ?  It's not listed as a dependency on https://github.com/ibm-messaging/iot-java.
Similarly, iotf/ext/lib/com.ibm.json4j is present and it's not listed as a dependency (gson is).
Both jars are referenced in `connectors/.classpath`.  Can the be removed?

The reason why I ask is that I'm having an issue in Eclipse related to developing the WebSocket client connector.  As part of the tests I need a WebSocket server and I'm using jetty componentry to create it.  The problem is that `connectors` is a single project with a single .classpath file.  My jetty WebSocket server needs its servlet-api-3.1.jar.  However the presence of javax.servlet_3.0.0.jar in the .classpath causes problems running my server from Eclipse.  This problem doesn't happen from ant as each connector has its own build.xml.

**Comment by ddebrunner** [comment]
I think I just put all the jars from the Iotf messaging client release into the ext/lib folder. They are probably not required, but I didn't have time to check to see which jars were required.

**Comment by dlaboss** [comment]
I ping'd iot-java https://github.com/ibm-messaging/iot-java/issues/14#issuecomment-188124832
The upshot is that they can be removed.
