### ISSUE TITLE
runiotfSensors.sh script - documentation on required parameter and IoTf setup

### ISSUE THREAD

**Issue by mnwone** [quarks-edge/quarks#53]
-bash-4.2$ ./runiotfsensors.sh
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at quarks.samples.connectors.iotf.IoTFSensors.main(IoTFSensors.java:39)

I'm looking for information (ex. README)  on how to run runiotfSensor.sh.

Excerpt from runiotfSensor.sh:
.# Runs the Sample MQTT Publisher or Subscriber
# 

.# ./runmqttsample.sh pub
.# ./runmqttsample.sh sub
export CLASSPATH=${quarks}/samples/lib/quarks.samples.connectors.jar
java quarks.samples.connectors.iotf.IoTFSensors $1

Where to find information on how to specify '$1'?  Also the comments on MQTT probably need updating.

Per IoTFSensors.java requires a deviceCfg file. 
It looks like I need to set up IoTF – is the standard setup sufficient to run this script?

**Comment by dlaboss** [comment]
There is a newer version of runiotfSensor.sh, and maybe the sample itself, in the repo that lacks those copy/paste issues.  Not sure if more doc is still required (I'm not the author of the sample).

**Comment by dlaboss** [comment]
I'm going to close this.  Pls reopen if after getting the latest version there are still issues.
