### ISSUE TITLE
Add Range analytic utility?

### ISSUE THREAD

**Issue by dlaboss** [quarks-edge/quarks#54]
A common sensor analytic is to filter for values being within a range.  It's common for range values to be initialized from static properties files and/or dynamically set from external sources.

The [Guava Range](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Range.html) class offers a very convenient way for dealing with ranges.  The Guava jar is significant in size.  There are ways to mitigate that [using ProGuard](https://github.com/google/guava/wiki/UsingProGuardWithGuava) though as noted at that link it's not clear that approach would be appropriate for quarks/library use.

The SensorAnalytics sample app contains a [simple Range implementation](https://github.com/quarks-edge/quarks/blob/master/samples/apps/src/main/java/quarks/samples/apps/Range.java) of a portion of the Guava Range API.  Should that be incorporated into `quarks.analytics.sensors` to "make the simple simple"?

**Comment by ddebrunner** [comment]
Any thoughts on what this would look like?

Could I use a range to specify the in band region for a deadband filter?

**Comment by dlaboss** [comment]
Yup, a Range could be used to specify the in-band region.  Shall I create a pull request with the exact code for evaluation/comment?  Click on the above "simple Range implementation" link to see the current (not tidied up) code.

```
Range r = Range.closedOpen(3,7);    // Integer range between 3-inclusive and 7-exclusive
r = Range.valueOf("[3..7)", Integer.class);  // same thing
s = s.filter(tuple -> r.contains(tuple));  // pass only tuples in the range

// Range is generic type.
// There are the full combination of two bound range ctors and
// ctors for those with only a single bound, e.g., Range.atMost(7)  //  (-INF..7]
```

**Comment by ddebrunner** [comment]
Why not take the Guava range implementation?

**Comment by dlaboss** [comment]
pls clarify exactly what you mean by that.

**Comment by ddebrunner** [comment]
Take the Range.java source from Guava

**Comment by dlaboss** [comment]
I've avoided looking at that source (just the javadoc).  Don't know if its self contained.  I guess its licensing [COPYING](https://github.com/google/guava/blob/master/COPYING) allows that as long as we make the necessary attributions, etc?  How would you bundle it / expose it - e.g., in the analytics jar, with its `com.google.common.collect` package name?

**Comment by dlaboss** [comment]
Moved to https://issues.apache.org/jira/browse/QUARKS-78
