### ISSUE TITLE
Discussion Question: Why use Quarks

### ISSUE THREAD

**Issue by kathyssaunders** [quarks-edge/quarks#57]
Recently one of my colleagues attended Spark Summit East and spoke with people about Quarks.  One of the questions he was asked was "Why wouldn't I just write Quarks myself?"  His answer was:
You always could, but Quarks removes the developer from having to write a lot of boiler-place code for things like:
    - Keeping track of the last ten minutes of data, or last _N_ items on a data stream.
    - Connecting to Kafka, MQTT, JDBC, files, and websockets.
I think that's a good answer, but wanted to ask if others have more input on this.  I can add it to our FAQs, but thought it was worth having a larger discussion on this topic.

**Comment by ddebrunner** [comment]
Isn't the question: "Why wouldn't I just code the complete application myself, not relying on Quarks?"

I think Quarks is a tool for edge analytics that allows you to be more productive in implementing an application that meets your needs. Quarks provides a consistent data model (streams and windows) and provides useful functionality, aggregations, joins, etc. you can use without having to implement it yourself.

Like anything, one can always write everything from scratch, but why would you, when there's a tool that provides useful functionality. It's a similar argument as to why do I need a database, I can just use files, and then you find having to build database like functionality like queries, aggregations, joins etc., rather than just starting with a tool like Apache Derby that is easy to use and provides value.

**Comment by kathyssaunders** [comment]
+1 Thanks for the editing of the question and the answer.  I do intend to
update the FAQ, but will wait for a bit to see if there are more comments.

**Comment by vdogaru** [comment]
I recently helped a colleague develop a Quarks app and, under time pressure, I wrote several processing steps into a single custom function.  I had to write code to buffer data tuples and process data one buffer at a time. This has quickly become a time sink. I spent more time writing code for managing multiple circular buffers than writing the actual application logic.

I'm writing iteration 2 now using the Quarks window API. The API removes the need to manage buffering, so I can focus now on writing the application logic in an aggregate function.

This is just a simple example. Looking forward, more things that would make using Quarks more compelling:
- My colleague had to write a custom file reader for '.wav' files, so it would help to have binary encoders and decoders for reading and writing audio and video files.
- Multiplexers/demultiplexers for audio and video streams.
- Data compression encoders and decoders to help reduce network traffic (and costs) when bandwidth is limited.
- Exposing more data analysis algorithms provided by the commons-math jar, which is already packaged with Quarks.

**Comment by ddebrunner** [comment]
@vdogaru indirectly brings up another good point, by using Quarks you can benefit the community by adding features to it as you find a need, such as a reader for '.wav' files. Thus you contribute to the community to other's benefit and in turn benefit from functionality contributed by others.

@vdogaru  Is it possible your colleague can contribute back reader for .wav files?

**Comment by vdogaru** [comment]
Great idea, I will ask if he is interested in contributing to Quarks.

**Comment by kathyssaunders** [comment]
I've been working on the wording for the FAQ.  How about this:

## Why do I need Quarks, rather than coding the complete application myself?

Quarks is a tool for edge analytics that allows you to be more productive. Quarks provides a consistent data model (streams and windows) and provides useful functionality, such as aggregations, joins, etc.  Using Quarks allows you to take advantage of this functionality, allowing you focus on your application needs.

**Comment by vlasov01** [comment]
I'm not aware if there is anything similar that can run on Android.

**Comment by mikespicer** [comment]
typo missing "to" :  ....... allowing you **to** focus on your application needs.

**Comment by kathyssaunders** [comment]
Thank you, Mike.  I'll fix that before updating.

**Comment by kathyssaunders** [comment]
Merged pull request https://github.com/quarks-edge/quarks.documentation/pull/52 to add the new FAQ
