### ISSUE TITLE
Add jQuery and jQuery-ui javascript libraries to the console?

### ISSUE THREAD

**Issue by home4slc** [quarks-edge/quarks#59]
I'd like to start adding a few widgets to the console (dialogs, etc) and also to come up with a consistent look and feel for the console.
If we add jQuery and jQuery-ui js libraries, I believe it would be a good base to do so.
Both libraries have either the MIT license or an MIT license with a few added clauses:

JQuery: https://github.com/jquery/jquery/blob/master/LICENSE.txt 
JqueryUI:   http://contribute.jquery.org/CLA/ 

Any thoughts on either the choice of libraries, or the licenses?

**Comment by ddebrunner** [comment]
On the licencing issues, if Quarks becomes an Apache incubator then allowed licences would be:

http://www.apache.org/legal/resolved.html#category-a

**Comment by ddebrunner** [comment]
I think you have the wrong link for JqueryUI

**Comment by home4slc** [comment]
@ddebrunner thanks for the link to the apache acceptable licenses.  MIT is listed.

For that link for JQuery I was trying to point out the section called "Licenses":

jQuery Foundation projects (code, documentation, and any other materials) are each released under the terms of the individual licenses as noted in the project's repository, or, if no separate license is specified, under the terms of the MIT license, with the following exception:

Copyright and related rights for sample code as defined in the project's LICENSE.txt file are waived via CC0. Rights to any change to existing sample code or contribution of new code denoted as sample code as defined in the project's LICENSE.txt file are waived via CC0.

**Comment by ddebrunner** [comment]
https://github.com/jquery/jquery-ui/blob/master/LICENSE.txt

**Comment by home4slc** [comment]
thanks ...
