### ISSUE TITLE
Add pub-sub model between jobs

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks#92]
Allow a running job to publish tuples that can be subscribed to by other running jobs.

Method in TStream:

`<U  super/extends T> TSink<T> publish(String topic, Class<U> streamType)`

Method in Topology

<T> TStream<T> subscribe(String topic, Class<T> streamType)`

This would be tied with a `PublishSubscribe` service that can be added to a provider.

Initial implementation would allow pub-sub within provider.

**Comment by ddebrunner** [comment]
This is related to #68

**Comment by dlaboss** [comment]
Why extend `Topology` and `TStream` instead of just defining a new connector?

**Comment by ddebrunner** [comment]
Good question.

My first reaction is that publish/subscribe is inherently part of the provider/runtime, therefore not a connector.

But a connector may make more sense, I'll think about it for a while.

**Comment by ddebrunner** [comment]
Pull request #98 implements pub/sub using the connector style suggested by @dlaboss
